name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    # set GOPATH
    - name: setup env
      shell: bash
      run: |
        echo "::set-env name=GOPATH::${{ github.workspace }}/go"
        echo "::add-path::${{ github.workspace }}/go/bin"

    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Build one commit before
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        path: go/src/github.com/${{ github.repository }}

    - name: Get one before dependencies
      run: |
        cd $GOPATH/src/github.com/${{ github.repository }}
        go get -v -d ./...

    - name: Build one before
      shell: bash
      run: |
        cd $GOPATH/src/github.com/${{ github.repository }}/cmd/utreexoserver
        go build -v -o oldutreexoserver
        ls

    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/${{ github.repository }}

    - name: Get dependencies
      run: |
        cd $GOPATH/src/github.com/${{ github.repository }}
        go get -v -d ./...

    - name: Build
      shell: bash
      run: |
        ls
        cd $GOPATH/src/github.com/${{ github.repository }}/cmd/utreexoserver
        go build -v
        ls
        cd $GOPATH/src/github.com/${{ github.repository }}/cmd/utreexoclient
        go build -v

    - name: Run unit tests
      shell: bash
      run: |
        cd $GOPATH/src/github.com/${{ github.repository }}
        go test -v ./accumulator

    - name: Run integration tests
      shell: bash
      run: |
        cd $GOPATH/src/github.com/${{ github.repository }}
        ls ./cmd/utreexoserver
        ./test/install_bitcoind.sh
        ./test/csn_bridge.sh "./cmd/utreexoserver/utreexoserver" "./cmd/utreexoclient/utreexoclient" "./cmd/utreexoserver/oldutreexoserver"
